In [98]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
import math
import random
import numpy as np
import pandas as pd
import scipy.io as sio
from sklearn.model_selection import train_test_split
from tensorflow.python.keras.utils.np_utils import to_categorical
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import matthews_corrcoef
from imblearn.metrics import geometric_mean_score
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,roc_auc_score
import warnings
warnings.filterwarnings("ignore")

In [108]:
data1 = pd.read_csv("../../dataset/NASA/JM1.csv")
data1.head()

loc  v(g)  ev(g)  iv(g)      n        v     l      d       i         e  \
0    1.1   1.4    1.4    1.4    1.3     1.30  1.30   1.30    1.30      1.30   
1    1.0   1.0    1.0    1.0    1.0     1.00  1.00   1.00    1.00      1.00   
2   72.0   7.0    1.0    6.0  198.0  1134.13  0.05  20.31   55.85  23029.10   
3  190.0   3.0    1.0    3.0  600.0  4348.76  0.06  17.06  254.87  74202.67   
4   37.0   4.0    1.0    4.0  126.0   599.12  0.06  17.19   34.86  10297.30   

   ...  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0  ...       2          2        2                  2      1.2        1.2   
1  ...       1          1        1                  1        1          1   
2  ...      51         10        8                  1       17         36   
3  ...     129         29       28                  2       17        135   
4  ...      28          1        6                  0       11         16   

  total_Op total_Opnd branchCount defects  
0      1.2        1.2         1.4   False  
1        1          1           1    True  
2      112         86          13    True  
3      329        271           5    True  
4       76         50           7    True  

[5 rows x 22 columns]

In [109]:
data1.describe()

loc          v(g)         ev(g)         iv(g)             n  \
count  10885.000000  10885.000000  10885.000000  10885.000000  10885.000000   
mean      42.016178      6.348590      3.401047      4.001599    114.389738   
std       76.593332     13.019695      6.771869      9.116889    249.502091   
min        1.000000      1.000000      1.000000      1.000000      0.000000   
25%       11.000000      2.000000      1.000000      1.000000     14.000000   
50%       23.000000      3.000000      1.000000      2.000000     49.000000   
75%       46.000000      7.000000      3.000000      4.000000    119.000000   
max     3442.000000    470.000000    165.000000    402.000000   8441.000000   

                  v             l             d             i             e  \
count  10885.000000  10885.000000  10885.000000  10885.000000  1.088500e+04   
mean     673.758017      0.135335     14.177237     29.439544  3.683637e+04   
std     1938.856196      0.160538     18.709900     34.418313  4.343678e+05   
min        0.000000      0.000000      0.000000      0.000000  0.000000e+00   
25%       48.430000      0.030000      3.000000     11.860000  1.619400e+02   
50%      217.130000      0.080000      9.090000     21.930000  2.031020e+03   
75%      621.480000      0.160000     18.900000     36.780000  1.141643e+04   
max    80843.080000      1.300000    418.200000    569.780000  3.107978e+07   

                  b             t        lOCode     lOComment      lOBlank  \
count  10885.000000  1.088500e+04  10885.000000  10885.000000  10885.00000   
mean       0.224766  2.046465e+03     26.252274      2.737529      4.62554   
std        0.646408  2.413154e+04     59.611201      9.008608      9.96813   
min        0.000000  0.000000e+00      0.000000      0.000000      0.00000   
25%        0.020000  9.000000e+00      4.000000      0.000000      0.00000   
50%        0.070000  1.128300e+02     13.000000      0.000000      2.00000   
75%        0.210000  6.342500e+02     28.000000      2.000000      5.00000   
max       26.950000  1.726655e+06   2824.000000    344.000000    447.00000   

       locCodeAndComment  
count       10885.000000  
mean            0.370785  
std             1.907969  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max           108.000000

In [110]:
data1.values.shape

(10885, 22)

In [114]:
data2=data1.values
for i in range(10885):
    if data2[i][21]==True:
        data2[i][21]=1
    else:
        data2[i][21]=0
data2[0]

array([1.1, 1.4, 1.4, 1.4, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 2, 2,
       2, 2, '1.2', '1.2', '1.2', '1.2', '1.4', 0], dtype=object)

In [115]:
X=np.array(data2).astype(float)

ValueError: could not convert string to float: '?'

In [11]:
X[:,:21]

array([[  1.1,   1.4,   1.4, ...,   1.2,   1.2,   1.4],
       [  1. ,   1. ,   1. , ...,   1. ,   1. ,   1. ],
       [ 24. ,   5. ,   1. , ...,  44. ,  19. ,   9. ],
       ...,
       [ 82. ,  11. ,   3. , ..., 285. , 190. ,  21. ],
       [ 10. ,   2. ,   1. , ...,  19. ,  13. ,   3. ],
       [ 28. ,   6. ,   5. , ...,  67. ,  37. ,  11. ]])

In [12]:
y=X[:,21]

In [13]:
X=X[:,0:21]

In [14]:
from imblearn.over_sampling import RandomOverSampler,SMOTE
#os =  RandomOverSampler()
X_res, y_res = SMOTE().fit_resample(X, y)
X_res.shape,y_res.shape

((898, 21), (898,))

In [15]:
X_res.shape
#X_res=X_res.reshape(898,21,1)
#X_res.shape

(898, 21)

In [19]:
import numpy as np
from sklearn import preprocessing
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
import datetime

def show_accuracy(predictLabel,Label):
    Label = np.ravel(Label).tolist()
    predictLabel = predictLabel.tolist()
    count = 0
    for i in range(len(Label)):
        if Label[i] == predictLabel[i]:
            count += 1
    return (round(count/len(Label),5))

class node_generator(object):
    def __init__(self, whiten = False):
        self.Wlist = []
        self.blist = []
        self.function_num = 0
        self.whiten = whiten

    def sigmoid(self, x):
        return 1.0/(1 + np.exp(-x))

    def relu(self, x):
        return np.maximum(x, 0)

    def tanh(self, x):
        return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))

    def linear(self, x):
        return x

    def orth(self, W):
        """
        目前看来，这个函数应该配合下一个generator函数是生成权重的
        """
        for i in range(0, W.shape[1]):
            w = np.mat(W[:,i].copy()).T
            w_sum = 0
            for j in range(i):
                wj = np.mat(W[:,j].copy()).T
                w_sum += (w.T.dot(wj))[0,0]*wj
            w -= w_sum
            w = w/np.sqrt(w.T.dot(w))
            W[:,i] = np.ravel(w)

        return W

    def generator(self, shape, times):
        for i in range(times):
            random.seed(i)
            W = 2*np.random.random(size=shape)-1
            if self.whiten == True:
                W = self.orth(W)   # 只在增强层使用
            b = 2*np.random.random() -1
            yield (W, b)

    def generator_nodes(self, data, times, batchsize, function_num):
        # 按照bls的理论，mapping layer是输入乘以不同的权重加上不同的偏差之后得到的
        # 若干组，所以，权重是一个列表，每一个元素可作为权重与输入相乘
        self.Wlist = [elem[0] for elem in self.generator((data.shape[1], batchsize), times)]
        self.blist = [elem[1] for elem in self.generator((data.shape[1], batchsize), times)]

        self.function_num = {'linear':self.linear,
                        'sigmoid': self.sigmoid,
                        'tanh':self.tanh,
                        'relu':self.relu }[function_num]  # 激活函数供不同的层选择
        # 下面就是先得到一组mapping nodes，再不断叠加，得到len(Wlist)组mapping nodes
        nodes = self.function_num(data.dot(self.Wlist[0]) + self.blist[0])
        for i in range(1, len(self.Wlist)):
            nodes = np.column_stack((nodes, self.function_num(data.dot(self.Wlist[i])+self.blist[i])))
        return nodes

    def transform(self,testdata):
        testnodes = self.function_num(testdata.dot(self.Wlist[0])+self.blist[0])
        for i in range(1,len(self.Wlist)):
            testnodes = np.column_stack((testnodes, self.function_num(testdata.dot(self.Wlist[i])+self.blist[i])))
        return testnodes

class scaler:
    def __init__(self):
        self._mean = 0
        self._std = 0
    
    def fit_transform(self,traindata):
        self._mean = traindata.mean(axis = 0)
        self._std = traindata.std(axis = 0)
        return (traindata-self._mean)/(self._std+0.001)
    
    def transform(self,testdata):
        return (testdata-self._mean)/(self._std+0.001)

class broadnet:
    def __init__(self, 
                 maptimes = 10, 
                 enhencetimes = 10,
                 map_function = 'linear',
                 enhence_function = 'linear',
                 batchsize = 'auto', 
                 reg = 0.001):
        
        self._maptimes = maptimes
        self._enhencetimes = enhencetimes
        self._batchsize = batchsize
        self._reg = reg
        self._map_function = map_function
        self._enhence_function = enhence_function
        
        self.W = 0
        self.pesuedoinverse = 0
        self.normalscaler = scaler()
        self.onehotencoder = preprocessing.OneHotEncoder(sparse = False)
        self.mapping_generator = node_generator()
        self.enhence_generator = node_generator(whiten = True)

    def fit(self,data,label,weight):
        if self._batchsize == 'auto':
            self._batchsize = data.shape[1]
        data = self.normalscaler.fit_transform(data)
        label = self.onehotencoder.fit_transform(np.mat(label).T)
        
        mappingdata = self.mapping_generator.generator_nodes(data,self._maptimes,self._batchsize,self._map_function)
        enhencedata = self.enhence_generator.generator_nodes(mappingdata,self._enhencetimes,self._batchsize,self._enhence_function)
        
        #print('number of mapping nodes {0}, number of enhence nodes {1}'.format(mappingdata.shape[1],enhencedata.shape[1]))
        #print('mapping nodes maxvalue {0} minvalue {1} '.format(round(np.max(mappingdata),5),round(np.min(mappingdata),5)))
        #print('enhence nodes maxvalue {0} minvalue {1} '.format(round(np.max(enhencedata),5),round(np.min(enhencedata),5)))
        
        inputdata = np.column_stack((mappingdata,enhencedata))
        pesuedoinverse = self.pinv(inputdata,self._reg,weight)
        self.W =  pesuedoinverse.dot(label)
        
        #print('W:', self.W)
        #print('W:', self.W.shape)  
    
    #改写伪逆矩阵算法，将权重输入
    def pinv(self,A,reg,weight):
        return np.mat(reg*np.eye(A.shape[1])+A.T.dot(weight).dot(A)).I.dot(A.T).dot(weight)
    
    def decode(self,Y_onehot):
        Y = []
        for i in range(Y_onehot.shape[0]):
            lis = np.ravel(Y_onehot[i,:]).tolist()
            Y.append(lis.index(max(lis)))
        return np.array(Y)
    
    def accuracy(self,predictlabel,label):
        label = np.ravel(label).tolist()
        predictlabel = predictlabel.tolist()
        count = 0
        for i in range(len(label)):
            if label[i] == predictlabel[i]:
                count += 1
        return (round(count/len(label),5))
        
    def predict(self,testdata):
        testdata = self.normalscaler.transform(testdata)
        test_mappingdata = self.mapping_generator.transform(testdata)
        test_enhencedata = self.enhence_generator.transform(test_mappingdata)
        
        test_inputdata = np.column_stack((test_mappingdata,test_enhencedata)) 
        #print('*predictlabel shape:',self.decode(test_inputdata.dot(self.W)).shape)
        #print('*predictlabel:', self.decode(test_inputdata.dot(self.W)))
        #print('*accuracy:',show_accuracy(self.decode(test_inputdata.dot(self.W)),testlabel))
        return self.decode(test_inputdata.dot(self.W))
    
    def addWeight(self,trainlabel):
        #对BLS设置加权，按照训练集中的label比例进行权重设置
        #求训练数据集中label为1的个数
        count=0
        for z in range(len(trainlabel)):
            #print ('个数 %d ' %z)
            #print('k_train_label:', k_train_label[z])
            if trainlabel[z]==1:
                count=count+1
        #print ('label为1的个数 %d ' %j)
        #print(count)
        #print(k_train_label.shape)
        #print(len(k_train_label))
        #权重设置 
        weight = np.zeros((len(trainlabel),len(trainlabel)))
        for i in range(len(trainlabel)):
            if trainlabel[i]==1:
                #weight[i,i]=0.618/count
                weight[i,i]=2*(len(trainlabel)-count)/len(trainlabel)
            else:
                #weight[i,i]=1/(len(k_train_label)-count)
                weight[i,i]=2*count/len(trainlabel)
        #print('Weight:', weight)
        return weight

In [20]:
#将数据集划分为训练集和测试集
traindata,testdata,trainlabel,testlabel = train_test_split(X_res,y_res,test_size=0.2,random_state = 0)
#print(traindata.shape,trainlabel.shape,testdata.shape,testlabel.shape)
#X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2)
#y_train = np_utils.to_categorical(y_train)
#y_test = np_utils.to_categorical(y_test)

In [21]:
k_acc_list, k_f1_list, k_auc_list, k_mcc_list, k_Gm_list=[],[],[],[],[]
#这里设置shuffle设置为ture就是打乱顺序在分配
kf = KFold(n_splits=10,shuffle=True,random_state=42)
for map_times in np.arange(15,36,5):
    acc_list_tmp, f1_list_tmp, auc_list_tmp, mcc_list_tmp,Gm_list_tmp=[],[],[],[],[]
    for enhance_times in np.arange(15, 36,5):
        for k, (train, test) in enumerate(kf.split(traindata, trainlabel)):
            # kf.split输出的是索引，所以由索引获取交叉后的训练集和测试集及标签
            k_train_data,k_train_label = traindata[train], trainlabel[train]
            k_test_data,k_test_label = traindata[test], trainlabel[test]           

            bls = broadnet(maptimes = map_times, 
                       enhencetimes = enhance_times,
                       map_function = 'relu',
                       enhence_function = 'relu',
                       batchsize =100,
                       reg = 0.001)

            #根据训练数据设置权重
            weight=bls.addWeight(k_train_label)

            #训练
            starttime = datetime.datetime.now()
            bls.fit(k_train_data,k_train_label,weight)
            endtime = datetime.datetime.now()
            #print('the training time of BLS is {0} seconds'.format((endtime - starttime).total_seconds()))

            #print('k_test_label:', k_test_label)
            #预测
            k_predict_label = bls.predict(k_test_data)
            #print('k_predict_label:', k_predict_label)

            #评价指标计算
            acc=accuracy_score(k_test_label,k_predict_label,normalize=True)
            fmeasure=f1_score(k_test_label,k_predict_label, average='weighted', labels=np.unique(k_test_label))
            try:
                auc=roc_auc_score(k_test_label,k_predict_label, average='macro', sample_weight=None)
            except ValueError:
                pass
            MCC=matthews_corrcoef(k_test_label,k_predict_label)
            Gmeasure=geometric_mean_score(k_test_label,k_predict_label, average='weighted')

            #将此次的十折交叉验证的结果 (10个)保存到pi_list_tmp中
            acc_list_tmp.append(acc)
            f1_list_tmp.append(fmeasure)
            auc_list_tmp.append(auc)
            mcc_list_tmp.append(MCC)
            Gm_list_tmp.append(Gmeasure)

        #求平均保存到k_acc_list中   
        k_average_acc=np.mean(acc_list_tmp)
        k_average_acc=round(k_average_acc,5)
        k_acc_list.append(k_average_acc)

        #求平均保存到k_f1_list中   
        k_average_f1=np.mean(f1_list_tmp)
        k_average_f1=round(k_average_f1,5)
        k_f1_list.append(k_average_f1)

        #求平均保存到k_auc_list中   
        k_average_auc=np.mean(auc_list_tmp)
        k_average_auc=round(k_average_auc,5)
        k_auc_list.append(k_average_auc)

        #求平均保存到k_mcc_list中   
        k_average_mcc=np.mean(mcc_list_tmp)
        k_average_mcc=round(k_average_mcc,5)
        k_mcc_list.append(k_average_mcc)

        #求平均保存到k_Gm_list中   
        k_average_Gm=np.mean(Gm_list_tmp)
        k_average_Gm=round(k_average_Gm,5)
        k_Gm_list.append(k_average_Gm)
        print(f'maptiems:{map_times}\tenhancetimes:{enhance_times}\tk_average_acc:{k_average_acc}\tk_average_f1:{k_average_f1}\tk_average_auc:{k_average_auc}\tk_average_mcc:{k_average_mcc}\tk_average_Gm:{k_average_Gm}\t')

k_acc_array=np.array(k_acc_list)
k_acc_array=k_acc_array.reshape(5,5)
# 一维最大值索引
#idx_max_ravel = np.argmax(k_acc_array)
# true索引
#idx_max = np.unravel_index(idx_max_ravel, k_acc_array.shape)
#print('max times:',idx_max)

k_f1_array=np.array(k_f1_list)
k_f1_array=k_f1_array.reshape(5,5)

k_auc_array=np.array(k_auc_list)
k_auc_array=k_auc_array.reshape(5,5)

k_mcc_array=np.array(k_mcc_list)
k_mcc_array=k_mcc_array.reshape(5,5)

k_Gm_array=np.array(k_Gm_list)
k_Gm_array=k_Gm_array.reshape(5,5)

sio.savemat('./data_remember/WBLS_Smote_CM1_MEbest.mat',{'acc':k_acc_array,'f1':k_f1_array,'auc':k_auc_array,'mcc':k_mcc_array,'Gm':k_Gm_array})

maptiems:15	enhancetimes:15	k_average_acc:0.89699	k_average_f1:0.89668	k_average_auc:0.89454	k_average_mcc:0.79595	k_average_Gm:0.89445	
maptiems:15	enhancetimes:20	k_average_acc:0.89072	k_average_f1:0.89016	k_average_auc:0.88907	k_average_mcc:0.78711	k_average_Gm:0.88898	
maptiems:15	enhancetimes:25	k_average_acc:0.89329	k_average_f1:0.89274	k_average_auc:0.89139	k_average_mcc:0.79112	k_average_Gm:0.89128	
maptiems:15	enhancetimes:30	k_average_acc:0.89035	k_average_f1:0.88981	k_average_auc:0.88888	k_average_mcc:0.78614	k_average_Gm:0.88877	
maptiems:15	enhancetimes:35	k_average_acc:0.88749	k_average_f1:0.88709	k_average_auc:0.88671	k_average_mcc:0.7804	k_average_Gm:0.88662	
maptiems:20	enhancetimes:15	k_average_acc:0.88163	k_average_f1:0.88157	k_average_auc:0.88229	k_average_mcc:0.76958	k_average_Gm:0.88222	
maptiems:20	enhancetimes:20	k_average_acc:0.87329	k_average_f1:0.8732	k_average_auc:0.87382	k_average_mcc:0.7518	k_average_Gm:0.87376	
maptiems:20	enhancetimes:25	k_average_acc:0.

In [1]:
starttime = datetime.datetime.now()
bls.fit(X_train,y_train)
endtime = datetime.datetime.now()
print('the training time of BLS is {0} seconds'.format((endtime - starttime).total_seconds()))

NameError: name 'broadnet' is not defined

In [64]:
predictlabel = bls.predict(X_test)
print(show_accuracy(predictlabel,y_test))

0.92222


In [65]:
#y_test, predictlabel（真实值，预测值）

#使用sklearn库实现
#ACC 
#accurary(准确率)：也就是说真实值是1，预测值也是1；真实值为0，预测值也为0。就是正确的分类，这是我们评价模型的最重要的一个指标
from sklearn.metrics import accuracy_score
#accuracy_score(y_test, predictlabel)
accurary=accuracy_score(y_test, predictlabel, normalize=True)#normalize：默认值为True，返回正确分类的比例；如果为False，返回正确分类的样本数
accurary

0.9222222222222223

In [66]:
#precision(精准率)：假如预测的正类的个数和预测个数的比重。 数值越高，就是表示越对
from sklearn.metrics import precision_score
precision=precision_score(y_test, predictlabel)
precision

0.8910891089108911

In [67]:
#recall(召回率）：样本中的正例有多少被预测正确了。真实值是正例1，在正例预测中所占的比重。假如我们比较考虑类别1的预测能力，可以使用这个标准。 数值越高 就是找的越全。
from sklearn.metrics import recall_score
recall=recall_score(y_test, predictlabel)
recall

0.967741935483871

In [68]:
#F1：综合评价一个模型的拟合能力。
#F-measure
from sklearn.metrics import f1_score
F1=f1_score(y_test, predictlabel)
F1

0.9278350515463919

In [69]:
# # 绘制P-R曲线
# #P-R曲线（精准率—召回率）：准确率和召回率互相影响，理想状态下肯定追求两个都高，但是实际情况是两者相互“制约”：追求准确率高，则召回率就低；追求召回率高，则通常会影响准确率。若两者都低，则一般是出了某种问题。
# import matplotlib.pyplot as plt
# def plot_pr_curve(rec_ls, pre_ls, pr_value=None, title=None):
#     label = "AUPR: " + str(pr_value)
#     plt.plot(rec_ls, pre_ls, 'r-', )
#     plt.plot([0, 1], [1, 0], 'k--', linewidth=0.8, label=label)
#     plt.axis([0, 1, 0, 1])
#     plt.xlabel('Recall')
#     plt.ylabel('Precision')
#     plt.title(title)
#     plt.legend(loc="lower left")  # 若需显示label,必须在show之前加这一句
#     plt.show()
# plot_pr_curve(recall, precision,"P-R Curve",'Precision/Recall Curve')

In [70]:
#计算ROC曲线的横纵坐标值，TPR，FPR
#TPR = TP/(TP+FN) = recall(真正例率，敏感度)       FPR = FP/(FP+TN)(假正例率，1-特异性)
from sklearn.metrics import roc_curve
roc_curve(y_test, predictlabel, pos_label=None, sample_weight=None, drop_intermediate=True)

(array([0.        , 0.12643678, 1.        ]),
 array([0.        , 0.96774194, 1.        ]),
 array([2, 1, 0]))

In [71]:
#AUC  
#计算ROC曲线下的面积就是AUC的值，the larger the better，值越大越好
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, predictlabel, average='macro', sample_weight=None)

0.9206525769373378

In [72]:
#MCC

from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, predictlabel)

0.8471892131665406